sources:
  hydrogen_v1:
    driver: csv
    args:
      urlpath: 's3://phy240060/configurations/hydrogen_v1.csv'
      storage_options:
        anon: false
        endpoint_url: 'https://uri.osn.mghpcc.org'

    description: "QMC HAMM Hydrogen Data"
    metadata:
      origin: "Example data"
      version: "1.0"
